### ISSUE TITLE
Stream goes black when playing Ocarina of Time 3D (Both JPN and USA copies)

### ISSUE THREAD

**Issue by toastydepression** [JennaScvl/Twix#1]
I tried streaming a JPN copy of Ocarina of Time 3D, yet it either went black or would freeze until I'd come back to the homescreen. I then tried another JPN game (Dragon Quest XI) to see if the issue was region specific, but this worked perfectly. I then tried a USA copy of Ocarina of Time 3D, and it yielded the same results as my JPN copy. This issue seems to (so far) be exclusive to Ocarina of Time 3D, as I tried Majora's Mask and it worked without issues.

**Comment by JennaScvl** [comment]
This is 100% absolutely not Twix's fault. Ocarina of Time switches off the wifi on the device when running.
Reddit has a workaround here, but as I no longer have a 3DS because mine was stolen, I cannot verify that this works.
https://www.reddit.com/r/3dspiracy/comments/1cn4vcw/ocarina_of_time_3d_and_snickerstream/

**Comment by toastydepression** [comment]
> This is 100% absolutely not Twix's fault. Ocarina of Time switches off the wifi on the device when running. Reddit has a workaround here, but as I no longer have a 3DS because mine was stolen, I cannot verify that this works. https://www.reddit.com/r/3dspiracy/comments/1cn4vcw/ocarina_of_time_3d_and_snickerstream/

I was not aware of this- Apologies for the confusion and thank you very much for the information!
